### PR TITLE
part A from issue #133

### PR DESCRIPTION
**Pull request by drop-lt**

### CODE REVIEW

**Review by drop-lt — COMMENTED** [review]
part 2

**Comment by fruitcake5** [comment]
Adding the margin when hovered is clunky, do it when a channel is actively being dragged

**Comment by drop-lt** [comment]
so no hover, just focus?

**Comment by fruitcake5** [comment]
Dragging is done with jquery, add the class then 

css cant do everything

**Comment by drop-lt** [comment]
i dont know jquery bro.

**Comment by fruitcake5** [comment]
You can use vanilla js to do it too

**Comment by drop-lt** [comment]
i prefer not doing it tho, css errors are easier to see and fix, and i dont know where do i even put it too, so better just part A

**Comment by superjacobl** [comment]
> Dragging is done with jquery, add the class then
> 
> css cant do everything

no its not, i used plain javascript for the dragging

**Comment by fruitcake5** [comment]
> no its not, i used plain javascript for the dragging

Wow thats a surprise lmao

**Comment by SpikeViper** [comment]
I'd prefer this to be done properly with js than popping up whenever a user hovers

**Pull request closed without merging**
