### PR TITLE
Update FAQ.md

### PR DESCRIPTION
**Pull request by Coca16**
I put it through Grammarly I promise it isn't dumb (and if it is I blame it not me)

### CODE REVIEW

**Comment by Snails-Of-Wrath** [comment]
I will proofread this

**Comment by Snails-Of-Wrath** [comment]
If any of this changes the meaning of the sentence, let me know.

Line 7:
> If you have a issues/suggestions it is recommended you use the [Valour Github Issues](https://github.com/Vooper-Media-LLC/Valour/issues) but before submitting any issue it is advised you also check the [Development Board](https://github.com/SpikeViper/Valour/projects/1) for suggestions and [Bug Triage Board](https://github.com/SpikeViper/Valour/projects/2) for bug issues.

Change to: If you have an issue/suggestion, it is recommended you use the [Valour Github Issues](https://github.com/Vooper-Media-LLC/Valour/issues). But before submitting any issue, it is advised you also check the [Development Board](https://github.com/SpikeViper/Valour/projects/1) for suggestions and [Bug Triage Board](https://github.com/SpikeViper/Valour/projects/2) for bug issues.

Line 9
> It is not planned to have a voice chat due to the high cost of hosting until there is a viable product and the funding.

Change to: It is not planned to have a voice chat due to the high cost of hosting. It will not be considered until there is a viable product and funding.

Line 15
> Valour will eventually have a mobile version on App Store and Play Store but as of now there is mobile support on the web if you do want to use it.

Change to: Valour will eventually have a mobile version on App Store and Play Store. But as of now, there is mobile support on the web if you want to use it.

Line 17
> There are options to make websites to be like apps on browsers like Chrome/Edge for phones and computers.

Change to: There are options to make websites act like apps on browsers like Chrome/Edge for phones and computers.

Line 21
> Due to Valour's AGPL3 license, you can modify or use Valour however you want however it must be opensource. For more info visit [LICENSE](https://github.com/SpikeViper/Valour/blob/main/LICENSE). It is also required to have you have signed commits when working on Valour itself which you can find documentation on [here](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification).

Change to; Due to Valour's AGPL3 license, you can modify or use Valour however you want, but it must be opensource. For more info, visit [LICENSE](https://github.com/SpikeViper/Valour/blob/main/LICENSE). It is required that you sign commits when working on Valour itself, which you can find documentation on [here](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification).

Line 25
> System roles would be applied to every planet within the system. This would also apply the permission the system user has onto the planet and planets would have their roles as well. This means if someone was a system admin they would also be an admin on planets within the system almost acting like planets within a single planet.

(I hope I kept the original meaning of this one)

Change to: A system role and its permissions are applied to every planet within the system. This means, if someone is a system admin, they would also be an admin on planets within the system, almost acting like planets within a single system. (I think you meant system when you said planet in the last word of the sentence)

Line 29
> Yes, there will be bots. You can use your account for self-botting as well if you wish.

Change to: Yes, there will be bots. You can also use your personal account for botting.

Line 35
> Valour will prioritize user reports that break the law such as doxxing, illegal material, extortion, etc... We will also need to confirm if a user did send certain messages if required to confirm a report. However, Valour will not punish people for being offensive and only assure safety and law.

(The first sentence sort of made it sound like the user reports themselves were breaking the law, had to rephrase much of this sentence. If its meaning isn't kept, let me know.)
Change to: Valour will prioritize user reports of activity that breaks the law; this illegal activity includes but is not limited to: doxxing, illegal material, or extortion. Valour will not punish users for being offensive but will assure that safety and law are upkept.

**Review by brndnln — CHANGES_REQUESTED** [review]
**From @Snails-Of-Wrath**:
If any of this changes the meaning of the sentence, let me know.

Line 7:
> If you have a issues/suggestions it is recommended you use the [Valour Github Issues](https://github.com/Vooper-Media-LLC/Valour/issues) but before submitting any issue it is advised you also check the [Development Board](https://github.com/SpikeViper/Valour/projects/1) for suggestions and [Bug Triage Board](https://github.com/SpikeViper/Valour/projects/2) for bug issues.

Change to: If you have an issue/suggestion, it is recommended you use the [Valour Github Issues](https://github.com/Vooper-Media-LLC/Valour/issues). But before submitting any issue, it is advised you also check the [Development Board](https://github.com/SpikeViper/Valour/projects/1) for suggestions and [Bug Triage Board](https://github.com/SpikeViper/Valour/projects/2) for bug issues.

Line 9
> It is not planned to have a voice chat due to the high cost of hosting until there is a viable product and the funding.

Change to: It is not planned to have a voice chat due to the high cost of hosting. It will not be considered until there is a viable product and funding.

Line 15
> Valour will eventually have a mobile version on App Store and Play Store but as of now there is mobile support on the web if you do want to use it.

Change to: Valour will eventually have a mobile version on App Store and Play Store. But as of now, there is mobile support on the web if you want to use it.

Line 17
> There are options to make websites to be like apps on browsers like Chrome/Edge for phones and computers.

Change to: There are options to make websites act like apps on browsers like Chrome/Edge for phones and computers.

Line 21
> Due to Valour's AGPL3 license, you can modify or use Valour however you want however it must be opensource. For more info visit [LICENSE](https://github.com/SpikeViper/Valour/blob/main/LICENSE). It is also required to have you have signed commits when working on Valour itself which you can find documentation on [here](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification).

Change to; Due to Valour's AGPL3 license, you can modify or use Valour however you want, but it must be opensource. For more info, visit [LICENSE](https://github.com/SpikeViper/Valour/blob/main/LICENSE). It is required that you sign commits when working on Valour itself, which you can find documentation on [here](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification).

Line 25
> System roles would be applied to every planet within the system. This would also apply the permission the system user has onto the planet and planets would have their roles as well. This means if someone was a system admin they would also be an admin on planets within the system almost acting like planets within a single planet.

(I hope I kept the original meaning of this one)

Change to: A system role and its permissions are applied to every planet within the system. This means, if someone is a system admin, they would also be an admin on planets within the system, almost acting like planets within a single system. (I think you meant system when you said planet in the last word of the sentence)

Line 29
> Yes, there will be bots. You can use your account for self-botting as well if you wish.

Change to: Yes, there will be bots. You can also use your personal account for botting.

Line 35
> Valour will prioritize user reports that break the law such as doxxing, illegal material, extortion, etc... We will also need to confirm if a user did send certain messages if required to confirm a report. However, Valour will not punish people for being offensive and only assure safety and law.

(The first sentence sort of made it sound like the user reports themselves were breaking the law, had to rephrase much of this sentence. If its meaning isn't kept, let me know.)
Change to: Valour will prioritize user reports of activity that breaks the law; this illegal activity includes but is not limited to: doxxing, illegal material, or extortion. Valour will not punish users for being offensive but will assure that safety and law are upkept.

**From me**:
For the word "GitHub", the H should be capitalized. That is all I see wrong so far.

**Review by fruitcake5 — CHANGES_REQUESTED** [review]
Amazing guide:
line number
> current text

suggested change

---

7
> If you have a issues/suggestions it is recommended you use the [Valour Github Issues](https://github.com/Vooper-Media-LLC/Valour/issues) but before submitting any issue it is advised you also check the [Development Board](https://github.com/SpikeViper/Valour/projects/1) for suggestions and [Bug Triage Board](https://github.com/SpikeViper/Valour/projects/2) for bug issues.
 
If you have issues/suggestions it is recommended you use the [Valour Github Issues](https://github.com/Vooper-Media-LLC/Valour/issues), before creating an issue it is strongly advised you make sure no one else has submitted the issue, check the [Development Board](https://github.com/SpikeViper/Valour/projects/1) for suggestions and [Bug Triage Board](https://github.com/SpikeViper/Valour/projects/2) for bug issues.

9
> It is not planned to have a voice chat due to the high cost of hosting until there is a viable product and the funding.

It is not planned to have a voice chat until a viable product has released and funding has been received.

13
> Yes, they will be migrated.

Yes

15
> Valour will eventually have a mobile version on App Store and Play Store but as of now there is mobile support on the web if you do want to use it.

Valour will eventually have a mobile version on the App Store and Play Store but as of now there is mobile support on the web if you do want to use it.

17
> There are options to make websites to be like apps on browsers like Chrome/Edge for phones and computers.

There are options to make websites act like apps in browsers like Chrome/Edge on phones and computers.
21
> Due to Valour's AGPL3 license, you can modify or use Valour however you want however it must be opensource. For more info visit [LICENSE](https://github.com/SpikeViper/Valour/blob/main/LICENSE). It is also required to have you have signed commits when working on Valour itself which you can find documentation on [here](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification).

Due to Valour's AGPL3 license, you can modify and use Valour however you want, but it must also be open source. For more info, visit [LICENSE](https://github.com/SpikeViper/Valour/blob/main/LICENSE). It is required that you sign commits when working on Valour itself, which you can find documentation on [here](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification).

25
> System roles would be applied to every planet within the system. This would also apply the permission the system user has onto the planet and planets would have their roles as well. This means if someone was a system admin they would also be an admin on planets within the system almost acting like planets within a single planet.

makes sense as is to me

35
> Valour will prioritize user reports that break the law such as doxxing, illegal material, extortion, etc... We will also need to confirm if a user did send certain messages if required to confirm a report. However, Valour will not punish people for being offensive and only assure safety and law.

Valour will prioritize reports of activity that breaks the law, such as doxxing, illegal material and extortion. Valour will not punish people for being offensive and only assure safety and law.

**Review by fruitcake5 — CHANGES_REQUESTED** [review]
### I have a SpookVooper account, will I have to make a Valour account?
Yes, they will be migrated.

implies SV accounts will be migrated to valour?

**Review by brndnln — APPROVED** [review]
Looks good 👍

**Comment by Coca16** [comment]
> ### I have a SpookVooper account, will I have to make a Valour account?
> Yes, they will be migrated.
> 
> implies SV accounts will be migrated to valour?

Well Spike said he was going to make it so SV uses Valour for Oauth so yes?

**Comment by brndnln** [comment]
> I have a SpookVooper account, will I have to make a Valour account?
> 
> Yes, they will be migrated.
> 
> implies SV accounts will be migrated to valour?

Isnt that what is going to happen?

**Comment by fruitcake5** [comment]
the answer is misleading

you have not followed my requested change which was to make it `yes`

**Comment by fruitcake5** [comment]
smh

**Review by brndnln — CHANGES_REQUESTED** [review]
You should just not have changed it honestly. Just prepend `Yes.` to it.

**Review by fruitcake5 — APPROVED** [review]

**Review by brndnln — APPROVED** [review]
I am happy now. Less ambiguous. :shipit:

**Pull request merged**
