### PR TITLE
solution to issue #128

### PR DESCRIPTION
**Pull request by drop-lt**

### CODE REVIEW

**Review by brndnln — APPROVED** [review]
This should be good. Anyone else want to weigh in? 👍

**Comment by Snails-Of-Wrath** [comment]
It looks like a good solution. I haven't tested it so I'm not sure if the thickness is enough.

**Review by fruitcake5 — APPROVED** [review]
Should do the trick probably

**Comment by drop-lt** [comment]
i mean, i think 2-5 pixels will be enough

**Pull request merged**
