### PR TITLE
Add max message character count for both client and api

### PR DESCRIPTION
**Pull request by AidenWilkins**
Added a simple check in (Valour.Server) ChannelController.cs (368) and (Valour.Server)  ChannelWindowsComponent.razor (line 202) to check if messages are larger than 1000 characters and just ignores them

### CODE REVIEW

**Comment by fruitcake5** [comment]
1000 characters seems a bit low

**Review by brndnln — COMMENTED** [review]
This should be good, however I am not going to approve or deny as I do not know if this affects anything

**Comment by brndnln** [comment]
> 1000 characters seems a bit low

We could bump it up to 2000 (what discord has it at)

**Comment by Coca16** [comment]
As far as I remember this is supposed to be set by planet admins and not a hard limit

**Comment by superjacobl** [comment]
can someone make a issue, where we will have a 4k default limit and make a flag in Planet.cs to allow admins to set limit?

**Comment by superjacobl** [comment]
ah let me make it

**Review by brndnln — COMMENTED** [review]
Should theoretically be good.

**Comment by superjacobl** [comment]
I have added a temp 2,048 limit until we add server set limits.

**Pull request closed without merging**
